# Generated by Django 4.0.5 on 2022-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_email_confirmed_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_choices',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
